BEGIN;

DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "server";

COMMIT;

BEGIN;

CREATE TABLE "user" (
  user_id SERIAL UNIQUE PRIMARY KEY,
  fname VARCHAR(30) NOT NULL,
  lname VARCHAR(30) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  joined_date DATE NOT NULL DEFAULT now()
);

CREATE TABLE server (
  server_id SERIAL UNIQUE PRIMARY KEY,
  server_name VARCHAR(50) NOT NULL,
  server_url VARCHAR(255),
  created_date DATE NOT NULL DEFAULT now(),
  user_id INT NOT NULL
);

COMMIT;
